### ISSUE TITLE
qi 1 1 5 2 `qiMul` qi 1 0 0 1 fails

### ISSUE THREAD

**Issue by ion1** [ion1/quadratic-irrational#2]
The documentation for qiMul:

> Multiply two QIs if the square root terms are the same or zeros.

```qi 1 1 5 2 `qiMul` qi 1 0 0 1``` fails while ```qi 1 1 5 2 `qiMul` qi 1 0 5 1``` succeeds. The regression seems to have been introduced by commit 4aa08b63ffdbe30f7e5151e9018be1c5c941a764.

**Comment by Bodigrim** [comment]
Ah, sorry for this. Should be fixed now.

**Comment by ion1** [comment]
Thank you!
